development:
  adapter: postgresql
  encoding: unicode
  database: samsoffes_development
  host: localhost
  pool: 5
  username: samsoffes
  password:
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: samsoffes_test
  host: localhost
  pool: 5
  username: samsoffes
  password:
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: samsoffes_production
  host: localhost
  pool: 5
  username: samsoffes
  password:
  min_messages: WARNING
