development:
  adapter: postgresql
  encoding: unicode
  database: samsoffes_development
  pool: 5
  username: samsoffes
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: samsoffes_test
  pool: 5
  username: samsoffes
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: samsoffes_production
  pool: 5
  username: samsoffes
  password:
